


export const metadata = {
    title: 'View Detail Blog',
    description: 'Generated by demo',
}

export default function ViewDetailLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <>
            {children}
        </>
    )
}
